name: Build packages

on:
  push:
    branches: 
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install rpm 
          sudo apt-get install wget -y
          
      - name: Build RPM package
        run: |
          mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          cd ~/rpmbuild/BUILD
          wget https://raw.githubusercontent.com/RyuuShuvi/lab/main/calc_files.sh
          cd ../../
          cd ~/rpmbuild/SPECS
          wget https://raw.githubusercontent.com/RyuuShuvi/lab/main/calc_files.spec
          cd ../../
          rpmbuild -ba ~/rpmbuild/SPECS/calc_files.spec


      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            ~/rpmbuild/RPNS/**/*.rpm
            ~/rpmbuild/SRPMS/*.src.rpm
